set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
"Plugin 'vim-syntastic/syntastic'
Plugin 'tpope/vim-fugitive'
Plugin 'Raimondi/delimitMate'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Reference: http://vimdoc.sourceforge.net/htmldoc/options.html#:options
set nocompatible          " Turn off vi compatibility
filetype indent on        " Enable file type detection

set autoindent            " Copy indent from current line when starting a new line
set colorcolumn=80        " Show a colored bar at 80 characters
set complete=.,w,b,u,t,i,kspell
                          " Keyword completion options
set expandtab             " Use spaces instead of tabs
"set foldmethod=indent     " Enable line folding
set ignorecase            " Ignore case in search patterns
set incsearch             " Highlight search patterns
set laststatus=2          " Last window always has a statusline
set list                  " Show whitespace characters
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
                          " Strings to use in list mode
set nohlsearch            " Stop highlighting after search
set nowrap                " Turn off line wrapping
set number                " Turn on line numbering
set path+=**              " Define search paths
set relativenumber        " Shows line number relative to the cursor
set ruler                 " Show line information
set shiftround            " Use shiftwidths for indenting
set shiftwidth=4          " Number of spaces to use for each tab
set smarttab              " Use spaces instead of tabs
set softtabstop=4         " Number of spaces that a <Tab> counts for
set tabstop=4             " Number of spaces that a <Tab> in the file counts for
set tags=~/.tags          " Filenames for the tag command
set t_Co=256              " Set colors to 256
set wildmenu              " Command-line completion operates in an enhanced mode

syntax enable             " Turn on syntax highlighting

" Integrate with powerline fonts
let g:airline_powerline_fonts = 1
